### PR TITLE
Stop using local cache

### PR DESCRIPTION
**Pull request by joshaber**
This will fix the currently broken prebuild.

`bundle install` time doesn't terribly matter since we're using prebuilds and this way we can bump dependencies without needing to `bundle cache` again.

@bdmac do you know of any reason we _shouldn't_ do this? Anything else we should clean up?

### CODE REVIEW

**Comment by bdmac** [comment]
I think I was trying to optimize for if someone came in and tried to run `bundle` in the running environment. Without it having things already present locally it was significantly slower from what I remember.

**Comment by joshaber** [comment]
But they'd already be installed at prebuild time wouldn't they?

**Comment by joshaber** [comment]
Running `bundle` on this PR:

```
$ time bundle
Using rake 13.0.6
Using concurrent-ruby 1.1.10
Using i18n 1.12.0
Using minitest 5.16.3
Using tzinfo 2.0.5
Using activesupport 7.0.4
Using builder 3.2.4
Using erubi 1.11.0
Using racc 1.6.1
Using nokogiri 1.13.10 (x86_64-linux)
Using rails-dom-testing 2.0.3
Using crass 1.0.6
Using loofah 2.19.0
Using rails-html-sanitizer 1.4.3
Using actionview 7.0.4
Using rack 2.2.4
Using rack-test 2.0.2
Using actionpack 7.0.4
Using nio4r 2.5.8
Using websocket-extensions 0.1.5
Using websocket-driver 0.7.5
Using actioncable 7.0.4
Using globalid 1.0.0
Using activejob 7.0.4
Using activemodel 7.0.4
Using activerecord 7.0.4
Using marcel 1.0.2
Using mini_mime 1.1.2
Using activestorage 7.0.4
Using mail 2.7.1
Using timeout 0.3.0
Using net-protocol 0.1.3
Using net-imap 0.3.1
Using net-pop 0.1.2
Using net-smtp 0.3.3
Using actionmailbox 7.0.4
Using actionmailer 7.0.4
Using actiontext 7.0.4
Using public_suffix 5.0.0
Using addressable 2.8.1
Using ast 2.4.2
Using backport 1.2.0
Using benchmark 0.2.0
Using parser 3.1.3.0
Using smart_properties 1.17.0
Using better_html 2.0.1
Using msgpack 1.6.0
Using bootsnap 1.15.0
Using bundler 2.3.26
Using matrix 0.4.2
Using regexp_parser 2.6.1
Using xpath 3.2.0
Using capybara 3.38.0
Using childprocess 4.1.0
Using io-console 0.5.11
Using reline 0.3.1
Using irb 1.5.1
Using debug 1.6.3
Using diff-lcs 1.5.0
Using e2mmap 0.1.0
Using rainbow 3.1.1
Using json 2.6.2
Using parallel 1.22.1
Using rexml 3.2.5
Using rubocop-ast 1.23.0
Using ruby-progressbar 1.11.0
Using unicode-display_width 2.3.0
Using rubocop 1.39.0
Using erb_lint 0.3.1
Using ffi 1.15.5
Using rb-fsevent 0.11.2
Using rb-inotify 0.10.1
Using listen 3.7.1
Using method_source 1.0.0
Using thor 1.2.1
Using zeitwerk 2.6.6
Using railties 7.0.4
Using rails 7.0.4
Using hotwire-livereload 1.2.2
Using importmap-rails 1.1.5
Using jaro_winkler 1.5.4
Using jbuilder 2.11.5
Using kramdown 2.4.0
Using kramdown-parser-gfm 1.1.0
Using puma 5.6.5
Using reverse_markdown 2.1.1
Using rubyzip 2.3.2
Using websocket 1.2.9
Using selenium-webdriver 4.6.1
Using tilt 2.0.11
Using webrick 1.7.0
Using yard 0.9.28
Using solargraph 0.47.2
Using sprockets 4.1.1
Using sprockets-rails 3.4.2
Using sqlite3 1.5.4 (x86_64-linux)
Using stimulus-rails 1.2.1
Using turbo-rails 1.3.2
Using webdrivers 5.2.0
Bundle complete! 17 Gemfile dependencies, 99 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

real    0m0.576s
user    0m0.450s
sys     0m0.080s
```

**Comment by bdmac** [comment]
Seems good to me!

**Comment by bdmac** [comment]
> But they'd already be installed at prebuild time wouldn't they?

I don't think I was seeing them installed and I assumed it was because bundler was trying to stick them into wherever the system ruby gempath was which felt like it wasn't part of the prebuild or didn't get saved/restored into the codespace afterwards like it did once I was caching it in the workspace directory.

**Review by bdmac — APPROVED** [review]

**Pull request merged**
